# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: caridac-geometriesx
author: Henrik Finsberg
logo: docs/_static/logo.png
copyright: "2024"
only_build_toc_files: true


execute:
  execute_notebooks: cache
  timeout: 3000

# Information about where the book exists on the web
repository:
  url: https://github.com/ComputationalPhysiology/cardiac-geometriesx # Online location of your book
  branch: main


html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify
    - html_image

sphinx:

  config:
    html_last_updated_fmt: "%b %d, %Y"
    nb_execution_show_tb: True
    suppress_warnings: ["mystnb.unknown_mime_type", "bibtex.duplicate_citation"]
    nb_custom_formats:  # https://jupyterbook.org/en/stable/file-types/jupytext.html#file-types-custom
        .py:
            - jupytext.reads
            - fmt: py
    codeautolink_concat_default: True
    intersphinx_mapping:
      basix : ["https://docs.fenicsproject.org/basix/main/python/", null]
      ffcx : ["https://docs.fenicsproject.org/ffcx/main/", null]
      ufl : ["https://docs.fenicsproject.org/ufl/main/", null]
      dolfinx : ["https://docs.fenicsproject.org/dolfinx/main/python", null]
      petsc4py: ["https://petsc.org/release/petsc4py", null]
      mpi4py: ["https://mpi4py.readthedocs.io/en/stable", null]
      numpy: ["https://numpy.org/doc/stable/", null]
      matplotlib: ["https://matplotlib.org/stable/", null]
      pyvista: ["https://docs.pyvista.org/", null]
      packaging: ["https://packaging.pypa.io/en/stable/", null]
      ldrb: ["https://finsberg.github.io/fenicsx-ldrb/", null]
      ukb: ["https://computationalphysiology.github.io/ukb-atlas/", null]

  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  - 'sphinx_copybutton'
  - 'sphinx_codeautolink'
  - 'sphinx.ext.intersphinx'

exclude_patterns: [".pytest_cache/*" ,"tests/.pytest_cache/*"]
