# # Cylindrical Geometries
# In this example we will create and visualize the three different cylindrical geometries:
# standard cylinder, D-shaped cylinder, racetrack cylinder, and elliptical cylinder, all generated by the
# `cardiac-geometriesx` library.

from pathlib import Path
from mpi4py import MPI
import pyvista
import dolfinx
import numpy as np
import cardiac_geometries

# We disable plotting if running in a non-interactive environment, which is typical for
# automated documentation builds (e.g., Jupyter Book).
if not getattr(pyvista, "OFF_SCREEN", True):
    pyvista.OFF_SCREEN = False

comm = MPI.COMM_WORLD

# ## 1. Standard Cylindrical Shell
# The standard cylinder is a hollow cylinder defined by an inner radius, an outer radius,
# and a height. Analytic fibers are calculated in a circumferential-longitudinal coordinate system.

geodir_std = Path("cylinder_standard")
if not geodir_std.exists():
    cardiac_geometries.mesh.cylinder(
        outdir=geodir_std,
        char_length=10.0,
        r_inner=10.0,
        r_outer=20.0,
        height=40.0,
        create_fibers=True,
        fiber_space="P_1",
        fiber_angle_endo=60,
        fiber_angle_epi=-60,
    )

geo_std = cardiac_geometries.geometry.Geometry.from_folder(
    comm=comm,
    folder=geodir_std,
)

# ### Mesh Visualization (Standard Cylinder)

vtk_mesh = dolfinx.plot.vtk_mesh(geo_std.mesh, geo_std.mesh.topology.dim)
grid = pyvista.UnstructuredGrid(*vtk_mesh)
plotter = pyvista.Plotter()
plotter.add_mesh(grid, show_edges=True)
plotter.view_xy()
if not pyvista.OFF_SCREEN:
    plotter.show()
else:
    plotter.screenshot("cylinder_standard_mesh.png")

# The facet markers for the standard cylinder:
print(geo_std.markers)

# ### Facet Tags Visualization (Standard Cylinder)

assert geo_std.ffun is not None
vtk_bmesh = dolfinx.plot.vtk_mesh(geo_std.mesh, geo_std.ffun.dim, geo_std.ffun.indices)
bgrid = pyvista.UnstructuredGrid(*vtk_bmesh)
bgrid.cell_data["Facet tags"] = geo_std.ffun.values
bgrid.set_active_scalars("Facet tags")
p = pyvista.Plotter(window_size=[800, 800])
p.add_mesh(bgrid, show_edges=True)
if not pyvista.OFF_SCREEN:
    p.show()
else:
    p.screenshot("cylinder_standard_facet_tags.png")

# ### Fiber Visualization (Standard Cylinder)

assert geo_std.f0 is not None
topology, cell_types, geometry = dolfinx.plot.vtk_mesh(geo_std.f0.function_space)
values = np.zeros((geometry.shape[0], 3), dtype=np.float64)
values[:, : len(geo_std.f0)] = geo_std.f0.x.array.real.reshape((geometry.shape[0], len(geo_std.f0)))
function_grid = pyvista.UnstructuredGrid(topology, cell_types, geometry)
function_grid["u"] = values
glyphs = function_grid.glyph(orient="u", factor=2.0)
grid = pyvista.UnstructuredGrid(*vtk_mesh)
plotter = pyvista.Plotter()
plotter.add_mesh(grid, style="wireframe", color="r")
plotter.add_mesh(glyphs)
plotter.view_xy()
if not pyvista.OFF_SCREEN:
    plotter.show()
else:
    plotter.screenshot("cylinder_standard_fiber.png")

# ## 2. D-shaped Cylinder
# The D-shaped cylinder is a thick cylindrical shell with one flat face running along its length.
# This geometry is created by intersecting a cylindrical shell with a cutting plane.
# Fiber orientations are a combination of analytic cylindrical coordinates and a slab-like orientation near the flat face, determined using the solution to the Laplace equation.

geodir_d = Path("cylinder_D_shaped")
if not geodir_d.exists():
    cardiac_geometries.mesh.cylinder_D_shaped(
        outdir=geodir_d,
        char_length=5.0,
        r_inner=13.0,
        r_outer=20.0,
        height=40.0,
        inner_flat_face_distance=10.0,
        outer_flat_face_distance=17.0,
        create_fibers=True,
        fiber_space="P_1",
    )

geo_d = cardiac_geometries.geometry.Geometry.from_folder(
    comm=comm,
    folder=geodir_d,
)

# ### Mesh Visualization (D-shaped Cylinder)

vtk_mesh = dolfinx.plot.vtk_mesh(geo_d.mesh, geo_d.mesh.topology.dim)
grid = pyvista.UnstructuredGrid(*vtk_mesh)
plotter = pyvista.Plotter()
plotter.add_mesh(grid, show_edges=True)
plotter.view_xy()
if not pyvista.OFF_SCREEN:
    plotter.show()
else:
    plotter.screenshot("cylinder_D_shaped_mesh.png")

# The facet markers for the D-shaped cylinder. Note the presence of the flat face markers (`INSIDE_FLAT` and `OUTSIDE_FLAT`):
print(geo_d.markers)

# ### Facet Tags Visualization (D-shaped Cylinder)

assert geo_d.ffun is not None
vtk_bmesh = dolfinx.plot.vtk_mesh(geo_d.mesh, geo_d.ffun.dim, geo_d.ffun.indices)
bgrid = pyvista.UnstructuredGrid(*vtk_bmesh)
bgrid.cell_data["Facet tags"] = geo_d.ffun.values
bgrid.set_active_scalars("Facet tags")
p = pyvista.Plotter(window_size=[800, 800])
p.add_mesh(bgrid, show_edges=True)
if not pyvista.OFF_SCREEN:
    p.show()
else:
    p.screenshot("cylinder_D_shaped_facet_tags.png")

# ### Fiber Visualization (D-shaped Cylinder)

assert geo_d.f0 is not None
topology, cell_types, geometry = dolfinx.plot.vtk_mesh(geo_d.f0.function_space)
values = np.zeros((geometry.shape[0], 3), dtype=np.float64)
values[:, : len(geo_d.f0)] = geo_d.f0.x.array.real.reshape((geometry.shape[0], len(geo_d.f0)))
function_grid = pyvista.UnstructuredGrid(topology, cell_types, geometry)
function_grid["u"] = values
glyphs = function_grid.glyph(orient="u", factor=2.0)
grid = pyvista.UnstructuredGrid(*vtk_mesh)
plotter = pyvista.Plotter()
plotter.add_mesh(grid, style="wireframe", color="r")
plotter.add_mesh(glyphs)
plotter.view_xy()
if not pyvista.OFF_SCREEN:
    plotter.show()
else:
    plotter.screenshot("cylinder_D_shaped_fiber.png")

# ## 3. Racetrack Cylinder
# The racetrack cylinder is a variant of the D-shaped cylinder with two parallel flat faces.
# This geometry is created by intersecting the cylindrical shell with two parallel cutting planes.
# The fiber generation method combines the analytic cylindrical model with two slab-like regions at the flat faces.

geodir_race = Path("cylinder_racetrack")
if not geodir_race.exists():
    cardiac_geometries.mesh.cylinder_racetrack(
        outdir=geodir_race,
        char_length=5.0,
        r_inner=13.0,
        r_outer=20.0,
        height=40.0,
        inner_flat_face_distance=10.0,
        outer_flat_face_distance=17.0,
        create_fibers=True,
        fiber_space="P_1",
    )

geo_race = cardiac_geometries.geometry.Geometry.from_folder(
    comm=comm,
    folder=geodir_race,
)

# ### Mesh Visualization (Racetrack Cylinder)

vtk_mesh = dolfinx.plot.vtk_mesh(geo_race.mesh, geo_race.mesh.topology.dim)
grid = pyvista.UnstructuredGrid(*vtk_mesh)
plotter = pyvista.Plotter()
plotter.add_mesh(grid, show_edges=True)
plotter.view_xy()
if not pyvista.OFF_SCREEN:
    plotter.show()
else:
    plotter.screenshot("cylinder_racetrack_mesh.png")

# The facet markers for the racetrack cylinder. Note the markers for the two sets of inner/outer flat faces (`INSIDE_FLAT1`, `OUTSIDE_FLAT1`, `INSIDE_FLAT2`, `OUTSIDE_FLAT2`):
print(geo_race.markers)

# ### Facet Tags Visualization (Racetrack Cylinder)

assert geo_race.ffun is not None
vtk_bmesh = dolfinx.plot.vtk_mesh(geo_race.mesh, geo_race.ffun.dim, geo_race.ffun.indices)
bgrid = pyvista.UnstructuredGrid(*vtk_bmesh)
bgrid.cell_data["Facet tags"] = geo_race.ffun.values
bgrid.set_active_scalars("Facet tags")
p = pyvista.Plotter(window_size=[800, 800])
p.add_mesh(bgrid, show_edges=True)
if not pyvista.OFF_SCREEN:
    p.show()
else:
    p.screenshot("cylinder_racetrack_facet_tags.png")

# ### Fiber Visualization (Racetrack Cylinder)

assert geo_race.f0 is not None
topology, cell_types, geometry = dolfinx.plot.vtk_mesh(geo_race.f0.function_space)
values = np.zeros((geometry.shape[0], 3), dtype=np.float64)
values[:, : len(geo_race.f0)] = geo_race.f0.x.array.real.reshape((geometry.shape[0], len(geo_race.f0)))
function_grid = pyvista.UnstructuredGrid(topology, cell_types, geometry)
function_grid["u"] = values
glyphs = function_grid.glyph(orient="u", factor=2.0)
grid = pyvista.UnstructuredGrid(*vtk_mesh)
plotter = pyvista.Plotter()
plotter.add_mesh(grid, style="wireframe", color="r")
plotter.add_mesh(glyphs)
plotter.view_xy()
if not pyvista.OFF_SCREEN:
    plotter.show()
else:
    plotter.screenshot("cylinder_racetrack_fiber.png")



# ## 4. Elliptical Cylinder
# The elliptical cylinder is a hollow cylinder with an elliptical cross-section, defined by inner and outer
# semi-major and semi-minor axes, and a height. Analytic fibers are calculated in an elliptical-circumferential-longitudinal
# coordinate system.

geodir_ellip = Path("cylinder_elliptical")
if not geodir_ellip.exists():
    cardiac_geometries.mesh.cylinder_elliptical(
        outdir=geodir_ellip,
        char_length=5.0,
        r_inner_x=15.0,
        r_outer_x=20.0,
        r_inner_y=10.0,
        r_outer_y=15.0,
        height=40.0,
        create_fibers=True,
        fiber_space="P_1",
    )

geo_ellip = cardiac_geometries.geometry.Geometry.from_folder(
    comm=comm,
    folder=geodir_ellip,
)

# ### Mesh Visualization (Elliptical Cylinder)

vtk_mesh = dolfinx.plot.vtk_mesh(geo_ellip.mesh, geo_ellip.mesh.topology.dim)
grid = pyvista.UnstructuredGrid(*vtk_mesh)
plotter = pyvista.Plotter()
plotter.add_mesh(grid, show_edges=True)
plotter.view_xy()
if not pyvista.OFF_SCREEN:
    plotter.show()
else:
    plotter.screenshot("cylinder_elliptical_mesh.png")

# The facet markers for the elliptical cylinder.
print(geo_ellip.markers)

# ### Facet Tags Visualization (Elliptical Cylinder)

assert geo_ellip.ffun is not None
vtk_bmesh = dolfinx.plot.vtk_mesh(geo_ellip.mesh, geo_ellip.ffun.dim, geo_ellip.ffun.indices)
bgrid = pyvista.UnstructuredGrid(*vtk_bmesh)
bgrid.cell_data["Facet tags"] = geo_ellip.ffun.values
bgrid.set_active_scalars("Facet tags")
p = pyvista.Plotter(window_size=[800, 800])
p.add_mesh(bgrid, show_edges=True)
if not pyvista.OFF_SCREEN:
    p.show()
else:
    p.screenshot("cylinder_elliptical_facet_tags.png")

# ### Fiber Visualization (Elliptical Cylinder)
assert geo_ellip.f0 is not None
topology, cell_types, geometry = dolfinx.plot.vtk_mesh(geo_ellip.f0.function_space)
values = np.zeros((geometry.shape[0], 3), dtype=np.float64)
values[:, : len(geo_ellip.f0)] = geo_ellip.f0.x.array.real.reshape((geometry.shape[0], len(geo_ellip.f0)))
function_grid = pyvista.UnstructuredGrid(topology, cell_types, geometry)
function_grid["u"] = values
glyphs = function_grid.glyph(orient="u", factor=2.0)
grid = pyvista.UnstructuredGrid(*vtk_mesh)
plotter = pyvista.Plotter()
plotter.add_mesh(grid, style="wireframe", color="r")
plotter.add_mesh(glyphs)
plotter.view_xy()
if not pyvista.OFF_SCREEN:
    plotter.show()
else:
    plotter.screenshot("cylinder_elliptical_fiber.png")
