name: Test package MPI


on:
  pull_request:
  push:
    branches: [main]



jobs:
  test-code:
    runs-on: ubuntu-22.04
    container: ghcr.io/fenics/dolfinx/dolfinx:stable
    env:
      DEB_PYTHON_INSTALL_LAYOUT: deb_system


    steps:
      - uses: actions/checkout@v5

      - name: Install package
        run: python3 -m pip install .[test]

      - name: Run tests
        run: mpirun -n 2 python3 -m pytest -v
